/**
 * LanguageRegistry - Detects programming languages from file extensions
 *
 * Provides static methods for language detection and configuration lookup.
 */

import { SupportedLanguage, type LanguageConfig } from './types.js';

/**
 * Language configuration registry
 */
export class LanguageRegistry {
  /**
   * Extension-to-language mapping
   */
  private static readonly extensionMap: Record<string, SupportedLanguage> = {
    // TypeScript
    '.ts': SupportedLanguage.TYPESCRIPT,
    '.tsx': SupportedLanguage.TYPESCRIPT,
    '.mts': SupportedLanguage.TYPESCRIPT,
    '.cts': SupportedLanguage.TYPESCRIPT,
    // JavaScript
    '.js': SupportedLanguage.JAVASCRIPT,
    '.jsx': SupportedLanguage.JAVASCRIPT,
    '.mjs': SupportedLanguage.JAVASCRIPT,
    '.cjs': SupportedLanguage.JAVASCRIPT,
    // Python
    '.py': SupportedLanguage.PYTHON,
    '.pyi': SupportedLanguage.PYTHON,
    '.pyx': SupportedLanguage.PYTHON,
    '.ipynb': SupportedLanguage.PYTHON,
    // Java
    '.java': SupportedLanguage.JAVA,
    '.class': SupportedLanguage.JAVA,
    '.jar': SupportedLanguage.JAVA,
    // Go
    '.go': SupportedLanguage.GO,
    // Rust
    '.rs': SupportedLanguage.RUST,
    '.rlib': SupportedLanguage.RUST,
    // C++
    '.cpp': SupportedLanguage.CPP,
    '.cc': SupportedLanguage.CPP,
    '.cxx': SupportedLanguage.CPP,
    '.c': SupportedLanguage.CPP,
    '.h': SupportedLanguage.CPP,
    '.hpp': SupportedLanguage.CPP,
    '.hxx': SupportedLanguage.CPP,
    // C#
    '.cs': SupportedLanguage.CSHARP,
    '.csx': SupportedLanguage.CSHARP,
    // Ruby
    '.rb': SupportedLanguage.RUBY,
    '.rake': SupportedLanguage.RUBY,
    '.gemspec': SupportedLanguage.RUBY,
    // PHP
    '.php': SupportedLanguage.PHP,
    '.phtml': SupportedLanguage.PHP,
    '.php3': SupportedLanguage.PHP,
    '.php4': SupportedLanguage.PHP,
    '.php5': SupportedLanguage.PHP,
    // Swift
    '.swift': SupportedLanguage.SWIFT,
    // Kotlin
    '.kt': SupportedLanguage.KOTLIN,
    '.kts': SupportedLanguage.KOTLIN,
    // SQL
    '.sql': SupportedLanguage.SQL,
    '.psql': SupportedLanguage.SQL,
    // YAML
    '.yaml': SupportedLanguage.YAML,
    '.yml': SupportedLanguage.YAML,
    // JSON
    '.json': SupportedLanguage.JSON,
    '.jsonc': SupportedLanguage.JSON,
    '.json5': SupportedLanguage.JSON,
    // Markdown
    '.md': SupportedLanguage.MARKDOWN,
    '.mdx': SupportedLanguage.MARKDOWN,
    '.markdown': SupportedLanguage.MARKDOWN,
  };

  /**
   * Language configurations
   */
  private static readonly configs: Record<SupportedLanguage, LanguageConfig> = {
    [SupportedLanguage.TYPESCRIPT]: {
      extensions: ['.ts', '.tsx', '.mts', '.cts'],
      commentPatterns: { single: '//', multi: ['/*', '*/'] },
      keywords: [
        'abstract',
        'as',
        'async',
        'await',
        'break',
        'case',
        'catch',
        'class',
        'const',
        'continue',
        'debugger',
        'declare',
        'default',
        'delete',
        'do',
        'else',
        'enum',
        'export',
        'extends',
        'finally',
        'for',
        'from',
        'function',
        'if',
        'implements',
        'import',
        'in',
        'instanceof',
        'interface',
        'let',
        'namespace',
        'new',
        'of',
        'package',
        'private',
        'protected',
        'public',
        'readonly',
        'return',
        'static',
        'super',
        'switch',
        'throw',
        'try',
        'type',
        'typeof',
        'var',
        'while',
        'with',
        'yield',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '=',
        '==',
        '===',
        '!=',
        '!==',
        '>',
        '<',
        '>=',
        '<=',
        '&&',
        '||',
        '!',
        '&',
        '|',
        '^',
        '~',
        '<<',
        '>>',
        '>>>',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '**=',
        '<<=',
        '>>=',
        '>>>=',
        '&=',
        '|=',
        '^=',
        '??',
        '?.',
        '=>',
      ],
    },
    [SupportedLanguage.JAVASCRIPT]: {
      extensions: ['.js', '.jsx', '.mjs', '.cjs'],
      commentPatterns: { single: '//', multi: ['/*', '*/'] },
      keywords: [
        'async',
        'await',
        'break',
        'case',
        'catch',
        'class',
        'const',
        'continue',
        'debugger',
        'default',
        'delete',
        'do',
        'else',
        'export',
        'extends',
        'finally',
        'for',
        'from',
        'function',
        'if',
        'import',
        'in',
        'instanceof',
        'let',
        'new',
        'of',
        'return',
        'static',
        'super',
        'switch',
        'throw',
        'try',
        'typeof',
        'var',
        'while',
        'with',
        'yield',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '=',
        '==',
        '===',
        '!=',
        '!==',
        '>',
        '<',
        '>=',
        '<=',
        '&&',
        '||',
        '!',
        '&',
        '|',
        '^',
        '~',
        '<<',
        '>>',
        '>>>',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '**=',
        '<<=',
        '>>=',
        '>>>=',
        '&=',
        '|=',
        '^=',
        '??',
        '?.',
        '=>',
      ],
    },
    [SupportedLanguage.PYTHON]: {
      extensions: ['.py', '.pyi', '.pyx'],
      commentPatterns: { single: '#', multi: ['"""', '"""'] },
      keywords: [
        'and',
        'as',
        'assert',
        'async',
        'await',
        'break',
        'class',
        'continue',
        'def',
        'del',
        'elif',
        'else',
        'except',
        'finally',
        'for',
        'from',
        'global',
        'if',
        'import',
        'in',
        'is',
        'lambda',
        'nonlocal',
        'not',
        'or',
        'pass',
        'raise',
        'return',
        'try',
        'while',
        'with',
        'yield',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '**',
        '//',
        '=',
        '==',
        '!=',
        '>',
        '<',
        '>=',
        '<=',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '**=',
        '//=',
        '&=',
        '|=',
        '^=',
        '>>=',
        '<<=',
        'and',
        'or',
        'not',
        'is',
        'in',
        '@',
      ],
    },
    [SupportedLanguage.JAVA]: {
      extensions: ['.java'],
      commentPatterns: { single: '//', multi: ['/*', '*/'] },
      keywords: [
        'abstract',
        'assert',
        'boolean',
        'break',
        'byte',
        'case',
        'catch',
        'char',
        'class',
        'const',
        'continue',
        'default',
        'do',
        'double',
        'else',
        'enum',
        'extends',
        'final',
        'finally',
        'float',
        'for',
        'goto',
        'if',
        'implements',
        'import',
        'instanceof',
        'int',
        'interface',
        'long',
        'native',
        'new',
        'package',
        'private',
        'protected',
        'public',
        'return',
        'short',
        'static',
        'strictfp',
        'super',
        'switch',
        'synchronized',
        'this',
        'throw',
        'throws',
        'transient',
        'try',
        'void',
        'volatile',
        'while',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '=',
        '==',
        '!=',
        '>',
        '<',
        '>=',
        '<=',
        '&&',
        '||',
        '!',
        '&',
        '|',
        '^',
        '~',
        '<<',
        '>>',
        '>>>',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '&=',
        '|=',
        '^=',
        '<<=',
        '>>=',
        '>>>=',
        '->',
        '::',
      ],
    },
    [SupportedLanguage.GO]: {
      extensions: ['.go'],
      commentPatterns: { single: '//', multi: ['/*', '*/'] },
      keywords: [
        'break',
        'case',
        'chan',
        'const',
        'continue',
        'default',
        'defer',
        'else',
        'fallthrough',
        'for',
        'func',
        'go',
        'goto',
        'if',
        'import',
        'interface',
        'map',
        'package',
        'range',
        'return',
        'select',
        'struct',
        'switch',
        'type',
        'var',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '=',
        '==',
        '!=',
        '>',
        '<',
        '>=',
        '<=',
        '&&',
        '||',
        '!',
        '&',
        '|',
        '^',
        '~',
        '<<',
        '>>',
        '&^',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '&=',
        '|=',
        '^=',
        '<<=',
        '>>=',
        '&^=',
        ':=',
        '...',
        '<-',
      ],
    },
    [SupportedLanguage.RUST]: {
      extensions: ['.rs'],
      commentPatterns: { single: '//', multi: ['/*', '*/'] },
      keywords: [
        'as',
        'async',
        'await',
        'break',
        'const',
        'continue',
        'crate',
        'dyn',
        'else',
        'enum',
        'extern',
        'false',
        'fn',
        'for',
        'if',
        'impl',
        'in',
        'let',
        'loop',
        'match',
        'mod',
        'move',
        'mut',
        'pub',
        'ref',
        'return',
        'self',
        'Self',
        'static',
        'struct',
        'super',
        'trait',
        'true',
        'type',
        'unsafe',
        'use',
        'where',
        'while',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '=',
        '==',
        '!=',
        '>',
        '<',
        '>=',
        '<=',
        '&&',
        '||',
        '!',
        '&',
        '|',
        '^',
        '~',
        '<<',
        '>>',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '&=',
        '|=',
        '^=',
        '<<=',
        '>>=',
        '->',
        '=>',
        '..',
        '..=',
        '?',
      ],
    },
    [SupportedLanguage.CPP]: {
      extensions: ['.cpp', '.cc', '.cxx', '.c', '.h', '.hpp', '.hxx'],
      commentPatterns: { single: '//', multi: ['/*', '*/'] },
      keywords: [
        'alignas',
        'alignof',
        'auto',
        'bool',
        'break',
        'case',
        'catch',
        'char',
        'class',
        'const',
        'constexpr',
        'continue',
        'decltype',
        'default',
        'delete',
        'do',
        'double',
        'else',
        'enum',
        'explicit',
        'export',
        'extern',
        'false',
        'float',
        'for',
        'friend',
        'goto',
        'if',
        'inline',
        'int',
        'long',
        'mutable',
        'namespace',
        'new',
        'noexcept',
        'nullptr',
        'operator',
        'override',
        'private',
        'protected',
        'public',
        'register',
        'return',
        'short',
        'signed',
        'sizeof',
        'static',
        'struct',
        'switch',
        'template',
        'this',
        'throw',
        'true',
        'try',
        'typedef',
        'typeid',
        'typename',
        'union',
        'unsigned',
        'using',
        'virtual',
        'void',
        'volatile',
        'while',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '=',
        '==',
        '!=',
        '>',
        '<',
        '>=',
        '<=',
        '&&',
        '||',
        '!',
        '&',
        '|',
        '^',
        '~',
        '<<',
        '>>',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '&=',
        '|=',
        '^=',
        '<<=',
        '>>=',
        '->',
        '::',
        '.*',
        '->*',
      ],
    },
    [SupportedLanguage.CSHARP]: {
      extensions: ['.cs', '.csx'],
      commentPatterns: { single: '//', multi: ['/*', '*/'] },
      keywords: [
        'abstract',
        'as',
        'base',
        'bool',
        'break',
        'byte',
        'case',
        'catch',
        'char',
        'checked',
        'class',
        'const',
        'continue',
        'decimal',
        'default',
        'delegate',
        'do',
        'double',
        'else',
        'enum',
        'event',
        'explicit',
        'extern',
        'false',
        'finally',
        'fixed',
        'float',
        'for',
        'foreach',
        'goto',
        'if',
        'implicit',
        'in',
        'int',
        'interface',
        'internal',
        'is',
        'lock',
        'long',
        'namespace',
        'new',
        'null',
        'object',
        'operator',
        'out',
        'override',
        'params',
        'private',
        'protected',
        'public',
        'readonly',
        'ref',
        'return',
        'sbyte',
        'sealed',
        'short',
        'sizeof',
        'stackalloc',
        'static',
        'string',
        'struct',
        'switch',
        'this',
        'throw',
        'true',
        'try',
        'typeof',
        'uint',
        'ulong',
        'unchecked',
        'unsafe',
        'ushort',
        'using',
        'var',
        'virtual',
        'void',
        'volatile',
        'while',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '=',
        '==',
        '!=',
        '>',
        '<',
        '>=',
        '<=',
        '&&',
        '||',
        '!',
        '&',
        '|',
        '^',
        '~',
        '<<',
        '>>',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '&=',
        '|=',
        '^=',
        '<<=',
        '>>=',
        '??',
        '?.',
        '=>',
        '->',
      ],
    },
    [SupportedLanguage.RUBY]: {
      extensions: ['.rb', '.rake', '.gemspec'],
      commentPatterns: { single: '#', multi: ['=begin', '=end'] },
      keywords: [
        'BEGIN',
        'END',
        'alias',
        'and',
        'begin',
        'break',
        'case',
        'class',
        'def',
        'defined?',
        'do',
        'else',
        'elsif',
        'end',
        'ensure',
        'false',
        'for',
        'if',
        'in',
        'module',
        'next',
        'nil',
        'not',
        'or',
        'redo',
        'rescue',
        'retry',
        'return',
        'self',
        'super',
        'then',
        'true',
        'undef',
        'unless',
        'until',
        'when',
        'while',
        'yield',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '**',
        '=',
        '==',
        '!=',
        '===',
        '>',
        '<',
        '>=',
        '<=',
        '<=>',
        '&&',
        '||',
        '!',
        '&',
        '|',
        '^',
        '~',
        '<<',
        '>>',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '**=',
        '&=',
        '|=',
        '^=',
        '<<=',
        '>>=',
        '=>',
        '..',
        '...',
      ],
    },
    [SupportedLanguage.PHP]: {
      extensions: ['.php', '.phtml', '.php3', '.php4', '.php5'],
      commentPatterns: { single: '//', multi: ['/*', '*/'] },
      keywords: [
        'abstract',
        'and',
        'array',
        'as',
        'break',
        'callable',
        'case',
        'catch',
        'class',
        'clone',
        'const',
        'continue',
        'declare',
        'default',
        'do',
        'echo',
        'else',
        'elseif',
        'empty',
        'enddeclare',
        'endfor',
        'endforeach',
        'endif',
        'endswitch',
        'endwhile',
        'eval',
        'exit',
        'extends',
        'final',
        'finally',
        'fn',
        'for',
        'foreach',
        'function',
        'global',
        'goto',
        'if',
        'implements',
        'include',
        'include_once',
        'instanceof',
        'insteadof',
        'interface',
        'isset',
        'list',
        'match',
        'namespace',
        'new',
        'or',
        'print',
        'private',
        'protected',
        'public',
        'readonly',
        'require',
        'require_once',
        'return',
        'static',
        'switch',
        'throw',
        'trait',
        'try',
        'unset',
        'use',
        'var',
        'while',
        'xor',
        'yield',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '**',
        '=',
        '==',
        '===',
        '!=',
        '!==',
        '>',
        '<',
        '>=',
        '<=',
        '<=>',
        '&&',
        '||',
        '!',
        '&',
        '|',
        '^',
        '~',
        '<<',
        '>>',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '**=',
        '&=',
        '|=',
        '^=',
        '<<=',
        '>>=',
        '??',
        '?.',
        '->',
        '=>',
        '...',
      ],
    },
    [SupportedLanguage.SWIFT]: {
      extensions: ['.swift'],
      commentPatterns: { single: '//', multi: ['/*', '*/'] },
      keywords: [
        'associatedtype',
        'async',
        'await',
        'break',
        'case',
        'catch',
        'class',
        'continue',
        'default',
        'defer',
        'deinit',
        'do',
        'else',
        'enum',
        'extension',
        'fallthrough',
        'false',
        'fileprivate',
        'for',
        'func',
        'guard',
        'if',
        'import',
        'in',
        'init',
        'inout',
        'internal',
        'is',
        'let',
        'nil',
        'open',
        'operator',
        'precedencegroup',
        'private',
        'protocol',
        'public',
        'repeat',
        'rethrows',
        'return',
        'self',
        'Self',
        'static',
        'struct',
        'subscript',
        'super',
        'switch',
        'throw',
        'throws',
        'true',
        'try',
        'typealias',
        'var',
        'where',
        'while',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '=',
        '==',
        '!=',
        '===',
        '!==',
        '>',
        '<',
        '>=',
        '<=',
        '&&',
        '||',
        '!',
        '&',
        '|',
        '^',
        '~',
        '<<',
        '>>',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '&=',
        '|=',
        '^=',
        '<<=',
        '>>=',
        '??',
        '...',
        '..<',
        '->',
      ],
    },
    [SupportedLanguage.KOTLIN]: {
      extensions: ['.kt', '.kts'],
      commentPatterns: { single: '//', multi: ['/*', '*/'] },
      keywords: [
        'abstract',
        'actual',
        'annotation',
        'as',
        'break',
        'by',
        'catch',
        'class',
        'companion',
        'const',
        'constructor',
        'continue',
        'data',
        'do',
        'else',
        'enum',
        'expect',
        'external',
        'false',
        'final',
        'finally',
        'for',
        'fun',
        'if',
        'import',
        'in',
        'infix',
        'init',
        'inline',
        'inner',
        'interface',
        'internal',
        'is',
        'lateinit',
        'noinline',
        'null',
        'object',
        'open',
        'operator',
        'out',
        'override',
        'package',
        'private',
        'protected',
        'public',
        'reified',
        'return',
        'sealed',
        'super',
        'suspend',
        'tailrec',
        'this',
        'throw',
        'true',
        'try',
        'typealias',
        'val',
        'var',
        'vararg',
        'when',
        'while',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '=',
        '==',
        '!=',
        '===',
        '!==',
        '>',
        '<',
        '>=',
        '<=',
        '&&',
        '||',
        '!',
        '&',
        '|',
        '^',
        '~',
        '<<',
        '>>',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '&=',
        '|=',
        '^=',
        '<<=',
        '>>=',
        '?.',
        '?:',
        '::',
        '..',
        '->',
      ],
    },
    [SupportedLanguage.SQL]: {
      extensions: ['.sql', '.psql'],
      commentPatterns: { single: '--', multi: ['/*', '*/'] },
      keywords: [
        'ADD',
        'ALL',
        'ALTER',
        'AND',
        'ANY',
        'AS',
        'ASC',
        'BACKUP',
        'BETWEEN',
        'CASE',
        'CHECK',
        'COLUMN',
        'CONSTRAINT',
        'CREATE',
        'DATABASE',
        'DEFAULT',
        'DELETE',
        'DESC',
        'DISTINCT',
        'DROP',
        'EXEC',
        'EXISTS',
        'FOREIGN',
        'FROM',
        'FULL',
        'GROUP',
        'HAVING',
        'IN',
        'INDEX',
        'INNER',
        'INSERT',
        'INTO',
        'IS',
        'JOIN',
        'KEY',
        'LEFT',
        'LIKE',
        'LIMIT',
        'NOT',
        'NULL',
        'ON',
        'OR',
        'ORDER',
        'OUTER',
        'PRIMARY',
        'PROCEDURE',
        'RIGHT',
        'ROWNUM',
        'SELECT',
        'SET',
        'TABLE',
        'TOP',
        'TRUNCATE',
        'UNION',
        'UNIQUE',
        'UPDATE',
        'VALUES',
        'VIEW',
        'WHERE',
      ],
      operators: [
        '+',
        '-',
        '*',
        '/',
        '%',
        '=',
        '!=',
        '<>',
        '>',
        '<',
        '>=',
        '<=',
        'AND',
        'OR',
        'NOT',
        'IN',
        'LIKE',
        'BETWEEN',
        'IS',
        '||',
      ],
    },
    [SupportedLanguage.YAML]: {
      extensions: ['.yaml', '.yml'],
      commentPatterns: { single: '#', multi: ['', ''] },
      keywords: ['true', 'false', 'null', 'yes', 'no', 'on', 'off'],
      operators: [':', '-', '?', '&', '*', '!', '|', '>', '---', '...'],
    },
    [SupportedLanguage.JSON]: {
      extensions: ['.json', '.jsonc', '.json5'],
      commentPatterns: { single: '', multi: ['', ''] },
      keywords: ['true', 'false', 'null'],
      operators: [':', ',', '{', '}', '[', ']'],
    },
    [SupportedLanguage.MARKDOWN]: {
      extensions: ['.md', '.mdx', '.markdown'],
      commentPatterns: { single: '', multi: ['<!--', '-->'] },
      keywords: [],
      operators: ['#', '##', '###', '####', '#####', '######', '-', '*', '>', '|', '`'],
    },
    [SupportedLanguage.UNKNOWN]: {
      extensions: [],
      commentPatterns: { single: '', multi: ['', ''] },
      keywords: [],
      operators: [],
    },
  };

  /**
   * Detect language from file path extension
   */
  static detect(filePath: string): SupportedLanguage {
    const normalized = filePath.toLowerCase();
    const dotIndex = normalized.lastIndexOf('.');
    if (dotIndex === -1) {
      return SupportedLanguage.UNKNOWN;
    }
    const ext = normalized.substring(dotIndex);
    return this.extensionMap[ext] ?? SupportedLanguage.UNKNOWN;
  }

  /**
   * Get language configuration
   */
  static getConfig(language: SupportedLanguage): LanguageConfig {
    return this.configs[language];
  }

  /**
   * Get all supported languages
   */
  static getSupportedLanguages(): SupportedLanguage[] {
    return Object.values(SupportedLanguage).filter(l => l !== SupportedLanguage.UNKNOWN);
  }

  /**
   * Get all supported extensions
   */
  static getSupportedExtensions(): string[] {
    return Object.keys(this.extensionMap);
  }

  /**
   * Check if a file extension is supported
   */
  static isExtensionSupported(extension: string): boolean {
    return extension in this.extensionMap;
  }
}
